gText_Birch_Welcome::
	.string "HOW?! As it Woie... “do you Do?”\p"
	.string "Welcome to 'De WOILD of POKé-MON!\p"
	.string "MY name is STOUT HALFLING.\p"
	.string "AND everyone calls me STOUT\l"
	.string "HALFLING.\p"
	.string "'De WOILD's PREMIER FOUR-POSTER\n"
	.string "BED TRANSPORTER-EXTRAORDINAIRE\l"
	.string "and NUMBA'-ONE ADVERTISING AGENT.\p"
	.string "And- I, just so Happen to be THE\n"
	.string "SHORT-HAND of the R.H.I.A.B.! AND-\p"
	.string "$"

gText_Birch_Pokemon::
	.string "'Dis is what we call a “POKé-MON,”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "'DIS WOILD, is wildly inhabited by\n"
	.string "'dese guys you're just gonna adore.\p"
	.string "an' BOY AR' YOU GOIN' T' LOVE IT!\p"
	.string "We humans live alongside POKé-MON,\n"
	.string "at times as friendly playmates, but\l"
	.string "mostly, as friendly weapons.\p"
	.string "And Tsometimes, we band together\n"
	.string "and blast music that does damage.\p"
	.string "BUT. Despite ower closeness, we\n"
	.string "don't know ANYTHING about POKé-MON.\p"
	.string "In fact, there are many, MANY\n"
	.string "secrets surrounding POKé-MON,\p"
	.string "that people have long avoided\n"
	.string "inspectigating due to inertia.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you ahre?$"

gText_Birch_BoyOrGirl::
	.string "Do you look like 'Dis?\n"
	.string "Or like... 'Dis?$"

gText_Birch_WhatsYourName::
	.string "Alll reight.\n"
	.string "What is your name?$"

gText_Birch_SoItsPlayer::
	.string "Ahh... So idt's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ahhh... OHK-AY!\p"
	.string "You're {PLAYER}{KUN} who's moving to MY\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I buhmember!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alll reight. Are you ready?\p"
	.string "Your very own adventia' is about\n"
	.string "to unfold.\p"
	.string "Take courage, and head into 'da\n"
	.string "woild of POKé-MON where Cash,\l"
	.string "Company, and Combat await!\p"
	.string "An' HEY!\l"
	.string "I'll be expectins' ya'.\p"
	.string "Come find me in my POKé-MON LAB.\p"
	.string "...\l"
	.string "SMOKE BOMB!!!\p"
	.string "$"
